
(function(){
 const replies={
  en:{welcome:'Hello! I am the Limoria Government Assistant. How can I help you?',unknown:'I can help with Limoria, the government, President Limon, the constitution, citizenship, economy, cities, tourism, and website navigation.',president:'President of the Republic of Limoria: Limon.',country:'Republic of Limoria is a fictional worldbuilding country. Capital: Limoria City. Population: 0. Area: 0 km². Motto: Unity • Progress • Prosperity.',gov:'Limoria uses a fictional constitutional republic model with a President, Prime Minister, National Assembly and Constitutional Court.',contact:'You can use the Contact page to send a demo message. This website is a fictional project.',help:'Try: “Who is the president?”, “Country information”, “Government”, “Constitution”, or “Tourism”.'},
  bn:{welcome:'হ্যালো! আমি লিমোরিয়া Government Assistant। কীভাবে সাহায্য করতে পারি?',unknown:'আমি লিমোরিয়া, সরকার, President Limon, সংবিধান, নাগরিকত্ব, অর্থনীতি, শহর, পর্যটন এবং ওয়েবসাইট নেভিগেশন সম্পর্কে সাহায্য করতে পারি।',president:'লিমোরিয়া প্রজাতন্ত্রের রাষ্ট্রপতি: Limon।',country:'লিমোরিয়া একটি কাল্পনিক worldbuilding দেশ। রাজধানী: Limoria City। জনসংখ্যা: ০। আয়তন: ০ কিমি²। মূলমন্ত্র: Unity • Progress • Prosperity.',gov:'লিমোরিয়ায় কাল্পনিক সাংবিধানিক প্রজাতন্ত্রের কাঠামো রয়েছে—President, Prime Minister, National Assembly এবং Constitutional Court।',contact:'Contact পেজ থেকে demo message পাঠানো যাবে। এটি একটি কাল্পনিক project।',help:'চেষ্টা করুন: “রাষ্ট্রপতি কে?”, “দেশের তথ্য”, “সরকার”, “সংবিধান” বা “পর্যটন”।'}
 };
 function lang(){return localStorage.getItem('limoria-language')==='bn'?'bn':'en'}
 function make(){
  if(document.querySelector('.lm-chat-launch'))return;
  const launch=document.createElement('button');launch.className='lm-chat-launch';launch.setAttribute('aria-label','Open Limoria chatbot');launch.innerHTML='💬';
  const box=document.createElement('section');box.className='lm-chat';box.setAttribute('aria-label','Limoria chatbot');
  box.innerHTML='<div class="lm-chat-head"><div class="lm-bot-avatar">L</div><div><div class="lm-chat-title">Limoria Assistant</div><div class="lm-chat-sub">Online • Government Information</div></div><button class="lm-chat-close" aria-label="Close">×</button></div><div class="lm-chat-messages"></div><div class="lm-chat-suggestions"><button class="lm-chip" data-q="president">President</button><button class="lm-chip" data-q="country">Country Info</button><button class="lm-chip" data-q="gov">Government</button><button class="lm-chip" data-q="help">Help</button></div><form class="lm-chat-form"><input class="lm-chat-input" autocomplete="off" placeholder="Type your question..."><button class="lm-chat-send">Send</button></form><div class="lm-chat-note">Fictional Limoria website assistant</div>';
  document.body.append(launch,box);
  const messages=box.querySelector('.lm-chat-messages'),input=box.querySelector('.lm-chat-input');
  function add(text,who){const d=document.createElement('div');d.className='lm-msg '+(who==='user'?'lm-user':'lm-bot');d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
  function answer(q){const s=q.toLowerCase(),r=replies[lang()];if(/president|রাষ্ট্রপতি|limon/.test(s))return r.president;if(/country|দেশ|population|জনসংখ্যা|area|আয়তন|capital|রাজধানী/.test(s))return r.country;if(/government|সরকার|minister|মন্ত্রণাল/.test(s))return r.gov;if(/contact|যোগাযোগ/.test(s))return r.contact;if(/help|সাহায্য|কি করতে|কী করতে/.test(s))return r.help;return r.unknown}
  function send(q){q=q.trim();if(!q)return;add(q,'user');input.value='';setTimeout(()=>add(answer(q),'bot'),180)}
  launch.onclick=()=>{box.classList.toggle('open');if(box.classList.contains('open')&&!messages.children.length)add(replies[lang()].welcome,'bot');if(box.classList.contains('open'))input.focus()};box.querySelector('.lm-chat-close').onclick=()=>box.classList.remove('open');box.querySelector('form').onsubmit=e=>{e.preventDefault();send(input.value)};box.querySelectorAll('.lm-chip').forEach(c=>c.onclick=()=>send(c.dataset.q));
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',make);else make();
})();